apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: query-layer
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos-query
    app.kubernetes.io/version: v0.25.2
  name: thanos-query
  namespace: monitoring-system
