apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: thanos-query-frontend
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/version: v0.25.2
  name: thanos-query-frontend
  namespace: monitoring-system
