apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: database-compactor
    app.kubernetes.io/instance: thanos-compact
    app.kubernetes.io/name: thanos-compact
    app.kubernetes.io/version: v0.25.2
  name: thanos-compact
  namespace: monitoring-system
